_BASE_: "../Base-RetinaFace.yaml"
MODEL:
  BACKBONE:
    NAME: "build_mnetv2_fpn_backbone"
  WEIGHTS: ""
  RETINANET:
    NUM_CONVS: 1
  RETINAFACE:
    NUM_LANDMARK: 4
    LANDMARK_REG_WEIGHTS: (10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0)
  MNET:
    WIDTH_MULT: 0.25
    OUT_FEATURES: ["mob3", "mob4", "mob5"]
  FPN:
    IN_FEATURES: ["mob3", "mob4", "mob5"]
    OUT_CHANNELS: 64
DATASETS:
  TRAIN: ("ccpd_base_train", "ccpd_danger_train", "ccpd_dlpr_train", "ccpd_slpr1_train", "ccpd_slpr_train")
  TEST: ()
SOLVER:
  IMS_PER_BATCH: 96
  STEPS: (2000000, 2300000)
  MAX_ITER: 2500000
  CHECKPOINT_PERIOD: 1000
TEST:
  KEYPOINT_OKS_SIGMAS: [1.0, 1.0, 1.0, 1.0]
VIS_PERIOD: 1000
OUTPUT_DIR: '/media/ps/A1/XPC/data/CCPD/ccpd_rotate_coco/output'