_BASE_: "../../../configs/Base-RetinaFace.yaml"
MODEL:
  BACKBONE:
    NAME: "build_mnetv2_fpn_backbone"
  WEIGHTS: "/media/ps/A1/XPC/data/CCPD/ccpd_rotate_coco/output/model_0335999.pth"
  RETINANET:
    NUM_CONVS: 1
    NUM_CLASSES: 1
  RETINAFACE:
    NUM_LANDMARK: 4
    LANDMARK_REG_WEIGHTS: (10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0)
  MNET:
    WIDTH_MULT: 0.25
    OUT_FEATURES: ["mob3", "mob4", "mob5"]
  FPN:
    IN_FEATURES: ["mob3", "mob4", "mob5"]
    OUT_CHANNELS: 64
INPUT:
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TRAIN: (320, 512, 640)
  CROP:
    ENABLED: True
    SIZE: [0.6, 0.6]
  MIN_SIZE_TEST: 320
  MAX_SIZE_TEST: 640
DATASETS:
  TRAIN: ("ccpd_base_train", "ccpd_danger_train", "ccpd_dlpr_train", "ccpd_slpr1_train", "ccpd_slpr_train")
  TEST: ()
SOLVER:
  IMS_PER_BATCH: 48
  STEPS: (200000, 230000)
  MAX_ITER: 250000
  CHECKPOINT_PERIOD: 1000
TEST:
  KEYPOINT_OKS_SIGMAS: [1.0, 1.0, 1.0, 1.0]
VIS_PERIOD: 100
OUTPUT_DIR: '/media/ps/A1/XPC/data/CCPD/ccpd_rotate_coco/output2'